### ISSUE TITLE
Implement "at most once" consumption

### ISSUE THREAD

**Issue by zorkian** [zorkian/marshal#11]
This is specified in the protocol but has not been implemented yet.

**Comment by zorkian** [comment]
@DrTall do you think this is necessary for an alpha release?

**Comment by DrTall** [comment]
I don't know what alpha release means in this context? But if I had to pick between having an ALO consumer and having no consumers at all I'd take the ALO consumer.

**Comment by zorkian** [comment]
ALO consumption is in and is now the default. I am asking if we need AMO consumption for alpha -- i.e. before we start documenting it on wiki pages and telling people we're comfortable with it being used for development. (We've told a few people -- but at alpha I would expect us to announce it as available.)

**Comment by DrTall** [comment]
Sorry if I was unclear in my previous comment. I think we should alpha the two of them independently. So whenever ALO is good enough to alpha let's do it, regardless of how far along AMO is.

**Comment by DrTall** [comment]
I am thinking of them as almost products because I doubt many customers need both for the same application.

**Comment by zorkian** [comment]
SG. Moved to Beta milestone.
