### ISSUE TITLE
Add instance ID to marshal/protocol

### ISSUE THREAD

**Issue by zorkian** [zorkian/marshal#14]
In the situation where you start up two consumers with the same client/group IDs, bad things could happen -- well, mostly double consumption of messages.

I propose adding an Instance ID to the Marshaler object. This will be randomly generated and can be used as a way to detect that a protocol message didn't come from us. Expected use would be, for example, if we see a Heartbeat that is from our group/client but not from us -- we can stop all work and exit, throwing exceptions.

@DrTall, thoughts?

**Comment by DrTall** [comment]
This seems like a good idea. We obviously can't stop abuse from someone intending to screw up the protocol, but protecting against the super obvious case of running the consumer twice in parallel seems like a good idea.

The only thing would be to make sure it can't end up preventing startup (when the Consumer restarts normally it'll get a new instance ID).
