### ISSUE TITLE
Switch to protobuf?

### ISSUE THREAD

**Issue by zorkian** [zorkian/marshal#15]
The current protocol is text based which is nice for some things, but it's also pretty verbose. A binary protocol would be more efficient, but also add a lot of work to implement in various languages. The current text based protocol has that ease of use advantage (plus readability for humans, a dubious benefit) but has extensibility problems.

@DrTall, thoughts on this?

**Comment by DrTall** [comment]
Keeping it dirt simple until there's a need for structured data seems fine to me. No matter what format you pick, somebody will be morally opposed to it (including plain text of course) so in the absence of any technical requirements might as well keep it simple.

**Comment by zorkian** [comment]
SG moving to Future milestone.
