### ISSUE TITLE
Code Review Notes

### ISSUE THREAD

**Issue by DrTall** [zorkian/marshal#3]
Not sure if an Issue is the best way to track this but github doesn't seem to have any review features outside a pull request.

I spent about an hour reading the code this morning so I haven't read everything yet, but I thought I would send over the comments I do have so far. My main macro-level concern is that I haven't found the code for the logic of "Somebody else has claimed a partition I think that _I_ have claimed, and I need to release my claim because it is stale.".

marshal.go
35: Is this a stale comment or does the Wait on line 91 do something different?

consumer.go
51,57: The comments say one of these is the offset of the 'next message' and the other is the offset of the '"next" message'. I don't understand the distinction.
100: Perhaps the caveat about Consumer needing to be discarded and rebuilt when partition count increases ought to be replicated in this comment block?
117: Consider making `behavior` a struct `behaviorOpts` so you can add more options later without breaking existing code.
347: If this returns an err it seems like we should probably not ignore it? If a consumer can't get Kafka metadata it should probably stop consuming after some timeout? Now, it may be that line 293 will cause this to happen but it's not 100% clear to me.
300: How would nowTime ever exactly equal claim.startTime? The claim start time only gets set in tryClaimPartition but nowTime is from line 277. I am guessing you are trying not to divide by zero on line 306 but if I am right that it should be impossible I think it ought to be its own if statement with its own comment. If I'm wrong about it being impossible then nevermind of course.
355: I don't understand why it is safe to hold on to any unhealthy partitions. If I understand the protocol correctly, other consumers may have already picked up these partitions if we haven't issued timely heartbeats.
225: How does this get cleaned up? It seems like line 300 will make sure this never gets unclaimed if we don't have a consumer running on it?
457: Would this be cleaner if there were a single message chan for the consumer (in addition to the per-claim chans) and there were just a single goroutine ranging over the list of claims to populate the consumer-level chan? This would avoid starvation for the individual claims and also make Consume more straightforward. You could just block on reading from this chan instead of busy waiting (lines 468-471).
489: How do we know the next offset is 1 more? If we are reading a compacted topic can't it be an arbitrary offset larger than the current one?
166,212,216,493,494: These reads/writes to lastHeartbeat appear to be unsynchronized across goroutines.

rationalizer.go:
137: How do we end up with multiple pending claims for a partition? We would need to get a call to ClaimPartition for this partition twice in the span of the rationalizer running right? But that call can only come from tryClaimPartition from claimPartitions from manageClaims from NewConsumer. Since NewConsumer is a singleton and all the calls after `go manageClaims` are blocking, I don't see how ClaimPartition could have two oustanding calls simultaneously.
150-155: Just call `fireEvents(topic.partitions[msg.PartID].ClientID == w.clientID && topic.partitions[msg.PartID].GroupID == w.groupID)`
169-173: Just call `fireEvents(true)` unless 172 is a typo in which case just call `fireEvents(msg.ClientID == w.clientID && msg.GroupID == w.groupID)`

**Comment by zorkian** [comment]
I think most of this was addressed in the latest refactor.

I think that actually the easiest way to do code review is via branch-and-pull-request like we were just doing. I'll do that for future code.
